context:
  version: "7.3.1"

package:
  name: cmake-js
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/cmake-js/-/cmake-js-${{ version }}.tgz
  sha256: 66cefad4e89097b1e610144180caff1e7c7918bd324dd7b68b7b572368d97aa7

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - cmake
    - nodejs

tests:
  - script:
      - cmake-js --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: CMake.js is a Node.js native addon build tool which works (almost) exactly like node-gyp, but instead of gyp, it is based on CMake build system.
  homepage: https://github.com/cmake-js/cmake-js
  repository: https://github.com/cmake-js/cmake-js

extra:
  recipe-maintainers:
    - danielnachun
